---
- name: Compute Engine Instance Examples
  hosts: localhost
  vars:
    masters:
      - instance-1
    quote: ''''
  tasks:
    #section for setting up network
#    - name: Create Firewall Rule w/Source Range
#      gce_net:
#        project_id: "{{ project_id }}"
#        credentials_file: "{{ credentials_file }}"
#        name: default
#        fwname: my-firewall-rule
#        allowed: tcp:80
#        state: present
#        src_range: ['0.0.0.0/0']
#        members: [{{(zone + '/') + (',' + zone + '/').join(masters)}}]
#        target_tags: http-server
#    - name: Allow tcp traffic on port 443 and 80 from any to infra
#      gce_net:
#        project_id: "{{ project_id }}"
#        credentials_file: "{{ credentials_file }}"
#        name: default
#        fwname: allow-http
#        allowed: tcp:80
#        target_tags: http-server
#        src_range: ['0.0.0.0/0']
#        state: present
      - set_fact:
         extended_etcd_endpoints_list: "{{ masters | map('regex_replace', '^(.*)$','europe-west3-b/\\1') | list  }}"
      - debug:
          var: extended_etcd_endpoints_list
      - name: Create master LB
        gce_lb:
          credentials_file: "{{ credentials_file }}"
          project_id: "{{ project_id }}"
          service_account_email: "{{ service_account_email }}"
          name: "{{ project_id }}-master-lb"
          region: "{{ region }}"
          members: "{{extended_etcd_endpoints_list}}"
          external_ip: "{{ project_id }}-master-lb-ip"
          port_range: 80
          httphealthcheck_name: "{{ project_id }}-master-lb-healthcheck"
          httphealthcheck_port: 80
          httphealthcheck_path: "/"
          httphealthcheck_interval: 10
          httphealthcheck_timeout: 10
          httphealthcheck_healthy_count: 3
          httphealthcheck_unhealthy_count: 3
          state: present
