---
- name: add the inventory file
  template:
    src: roles/bastion-prereq/templates/hosts.j2
    dest: /etc/ansible/hosts
- name: add the ansible.cfg file
  template:
    src: roles/bastion-prereq/templates/ansible.cfg.j2
    dest: /etc/ansible/ansible.cfg
- name: add docker-setup file for post processing
  copy:
    src: roles/bastion-prereq/files/docker-setup.yml
    dest: ~
- name: add install file to bastion for easy installation
  copy:
    src: roles/bastion-prereq/files/install.sh
    dest: ~
    mode: 0700

